# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_feeds', '0004_auto_20180130_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssfeedssettings',
            options={'verbose_name': 'RSS feed setting', 'verbose_name_plural': 'RSS feed settings'},
        ),
    ]
